CREATE TABLE USERS (Username varchar(20) NOT NULL, Name varchar(50) NOT NULL, Password varchar(30) NOT NULL, Role varchar(7) NOT NULL DEFAULT 'regular', PRIMARY KEY (Username));

CREATE TABLE MESSAGES (MID int NOT NULL AUTO_INCREMENT, Content varchar(5000) NOT NULL, Username varchar(20) NOT NULL, Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (MID), FOREIGN KEY (Username) REFERENCES USERS(Username) ON DELETE CASCADE ON UPDATE CASCADE );

-- CREATE TABLE MESSAGES_POSTED (UID int NOT NULL, MID int NOT NULL, PRIMARY KEY (UID, MID),
-- FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE ON UPDATE CASCADE,
-- FOREIGN KEY (MID) REFERENCES MESSAGES(MID) ON DELETE CASCADE ON UPDATE CASCADE);
